# Generated by Django 3.0.8 on 2020-11-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
